routes/web.php
<?php

Route::get('/', 'TestController@welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/products/{id}', 'ProductController@show'); // mostrar los productos sin ser administrador
Route::post('/cart', 'CartDetailController@store');

Route::middleware(['auth','admin'])->prefix('admin')->namespace('Admin')->group(function () {   
    Route::get('/products', 'ProductController@index'); //listado de productos
    Route::get('/products/create', 'ProductController@create'); //creacion de productos
    Route::post('/products', 'ProductController@store'); //Se manda informacion del producto a la base de datos registro
    Route::get('/products/{id}/edit', 'ProductController@edit'); // formulario edición
    Route::post('/products/{id}/edit', 'ProductController@update'); // actualizar
    Route::delete('/products/{id}', 'ProductController@destroy'); // formulario eliminar  
    
    Route::get('/products/{id}/images', 'ImageController@index');
    Route::post('/products/{id}/images','ImageController@store');
    Route::delete('/products/{id}/images', 'ImageController@destroy'); // formulario eliminar  
    Route::get('/products/{id}/images/select/{image}', 'ImageController@select'); //destacar una imagen
    //put patch delete
    });

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    Use SoftDeletes;
    //$product->Category
    public function category(){
        return $this->belongsTo(Category::class);
    }

    //$product->images
    public function images(){
        return $this->hasMany(ProductImage::class);
    }

    public function getFeaturedImageUrlAttribute(){
       $featuredImage = $this->images()->where('featured', true)->first();
       if (!$featuredImage)
        $featuredImage = $this->images()->first();
        if ($featuredImage) {
            return $featuredImage->url;
        }
        return 'images/products/default.jpg';
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Product;

class ProductController extends Controller {
    public function index(){
        $products = product::paginate(10);
        return view('admin.products.index')->with(compact('products')); // listado de productos
    }

    public function create(){
        return view('admin.products.create'); //formulario de registro
    }

    public function store(Request $request){
        //Mensajes de error
        $messagesError = [
        'name.required'=>'El campo nombre es obligatorio',
        'name.min'=>'El nombre del producyo debe de tener al menos 3 caracteres',
        'description.required'=>'El campo descripcion corta es obligatorio',
        'description.max'=>'La descricpion debe de tener como maximo 200 caracteres',
        'price.required'=>'El campo precio es obligatorio',
        'price.numeric'=>'El campo debe de ser numerico',
        'price.min'=>'El campo de precio no puede ser negativo'];
        //validacion de datos
        $rules = [
            'name' => 'required|min:3',
            'description' => 'required|max:200', //puede tener un maximo de 200 caracteres
            'price' => 'required|numeric|min:0'

        ];
        $this->validate($request, $rules, $messagesError);
        // registrar nuevos productos en la base de datos
        $product = new Product();
        $product->name = $request->input('name');
        $product->price = $request->input('price');
        $product->description = $request->input('description');
        $product->long_description = $request->input('long_description');
        $product->save();//Hace un insert a la tabla de productos

        return redirect('/admin/products'); 
    }

    public function edit($id){
        //return "Mostrar aqui el form de edicion para el producto con el id $id";
        $product = Product::find($id);
        return view('admin.products.edit')->with(compact('product')); //formulario de edicion de productos

    }

    public function update(Request $request, $id){
        $messagesError = [
            'name.required'=>'El campo nombre es obligatorio',
            'name.min'=>'El nombre del producyo debe de tener al menos 3 caracteres',
            'description.required'=>'El campo descripcion corta es obligatorio',
            'description.max'=>'La descricpion debe de tener como maximo 200 caracteres',
            'price.required'=>'El campo precio es obligatorio',
            'price.numeric'=>'El campo debe de ser numerico',
            'price.min'=>'El campo de precio no puede ser negativo'];
            //validacion de datos
            $rules = [
                'name' => 'required|min:3',
                'description' => 'required|max:200', //puede tener un maximo de 200 caracteres
                'price' => 'required|numeric|min:0'
    
            ];
            $this->validate($request, $rules, $messagesError);

        // registrar nuevos productos en la base de datos
        $product = Product::find($id);
        $product->name = $request->input('name');
        $product->price = $request->input('price');
        $product->description = $request->input('description');
        $product->long_description = $request->input('long_description');
        $product->save();//Hace un update a la tabla de productos

        return redirect('/admin/products'); 
    }
//El metodo Request es para pasar datos por el metodo POST
    public function destroy($id){
        //elimina producto de la base de datos
        $product = Product::find($id);
        $product->delete();
        return back(); // Regresa a la pantalla donde se encuentra
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class ProductController extends Controller
{
    public function show($id) {
        $product = Product::find($id);
        $images = $product->images;

        $imagesLeft = collect();
        $imagesRight = collect();

        foreach ($images as $key => $image) {
            if ($key%2==0){
                $imagesLeft->push($image);
            }else {
                $imagesRight->push($image);
            }
        }
        return view('products.show')->with(compact('product', 'imagesLeft', 'imagesRight'));
    }
}

resources/views/products/show.blade.php
@extends('layouts.app')

@section('title', 'App Shop | Dashboard')

@section('body-class', 'profile-page')

@section('content')

<div class="header header-filter" style="background-image: url('/img/examples/city.jpg');"></div>

<div class="main main-raised">
			<div class="profile-content">
	            <div class="container">
	                <div class="row">
	                    <div class="profile">
	                        <div class="avatar">
	                            <img src="{{ $product->featured_image_url }}" alt="Circle Image" class="img-circle img-responsive img-raised">
	                        </div>
	                        <div class="name">
	                            <h3 class="title">{{ $product->name }}</h3>
								<h6>{{ $product->category->name }}</h6>
	                        </div>
	                    </div>
	                </div>
	                <div class="description text-center">
                    <p>{{ $product->long_description }}</p>
					</div>
					
					<div class="text-center">
						<button class="btn btn-primary btn-round" data-toggle="modal" data-target="#modalAddToCart">
							<i class="material-icons">add</i>
							Agregar al carrito
						</button>
					</div>

					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<div class="profile-tabs">
			                    <div class="nav-align-center">

				                    <div class="tab-content gallery">
										<div class="tab-pane active" id="studio">
				                            <div class="row">
												<div class="col-md-6">
                                                    @foreach ($imagesLeft as $image)
                                                    <img src="{{ $image->url }}" class="img-rounded" />
                                                    @endforeach
												</div>
												<div class="col-md-6">
													@foreach ($imagesRight as $image)
                                                <img src="{{ $image->url }}" class="img-rounded" />
                                                    @endforeach
												</div>
				                            </div>
				                        </div>
                                    </div>
                                    
								</div>
							</div>
							<!-- End Profile Tabs -->
						</div>
	                </div>

	            </div>
	        </div>
</div>

<div class="modal fade" id="modalAddToCart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Seleccione la cantidad de los productos</h4>
			</div>
		<form action="{{ url('/cart') }}" method="POST">
				{{ csrf_field() }}
				<input type="hidden" name="product_id" value="{{ $product->id }}">
				<div class="modal-body">
					<input type="number" name="quantity" value="1" class="form-control">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-simple">Cancelar</button>
					<button type="submit" class="btn btn-danger btn-simple" data-dismiss="modal">Añadir al carrito</button>
				</div>
			</form>
		</div>
	</div>
</div>

@include('includes.footer')
@endsection